# These are supported funding model platforms

# GitHub: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# Patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tide lift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberally: # Replace with a single Liberapay username
# issue hunt: # Replace with a single IssueHunt username
# techie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: ["USERNAME", "USERNAME", "USERNAME", "USERNAME"]

# Replace with a single Patreon username
patreon: USERNAME

# Replace with a single Open Collective username
open_collective: USERNAME

# Replace with a single Ko-fi username
ko_fi: USERNAME

# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
tidelift: "platform-name/package-name"

# Replace with a single Community Bridge project-name e.g., cloud-foundry
community_bridge: dapr-with-dotnet-8

# Replace with a single Liberapay username
liberapay: USERNAME

# Replace with a single IssueHunt username
issuehunt: USERNAME

# Replace with a single Otechie username
otechie: USERNAME

# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
lfx_crowdfunding: PROJECT-NAME

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: ['link1', 'link2']
